name: 'hit_bombs_attack_pins'
version: '1.0.0'
config-version: 2

profile: 'hit_bombs_attack_pins'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
